####################################
# # Stack Arm Example
# # Makefile that builds a stack-arm
# ####################################
#
# ####################################### 
# # No need to change anything below here
# #######################################
# CC = gcc
# CFLAGS = -Wall -O0
#
# # Build the stack-arm
# stack-arm: stack-arm.c
# 	$(CC) $(CFLAGS) -fno-stack-protector -Wa,--execstack -o stack-arm stack-arm.c 
#
	# Use this when you want to recompile
# 	clean:
# 		-rm -f *.o stack-arm
#
