####################################
# # Desafio 01 Example
# # Makefile that builds a desafio01
# ####################################
#
# ####################################### 
# # No need to change anything below here
# #######################################
# CC = gcc
# CFLAGS = -Wall -O0
#
# # Build the stack-arm
# desafio01: desafio01.c
# 	$(CC) $(CFLAGS) -fno-stack-protector -Wa,--execstack -o desafio01 desafio01.c
#
# # Build hex2raw utility
# hex2raw: hex2raw.c
# 	$(CC) $(CFLAGS) -o hex2raw hex2raw.c 
#
	# Use this when you want to recompile
# 	clean:
# 		-rm -f *.o desafio01 hex2raw *~
#
